import {scenarios,initial,advance,restart,snapshot} from './model.mjs';
let state=initial(),timer=null;
const $=id=>document.getElementById(id);
function stop(){if(timer)clearInterval(timer);timer=null;}
function render(){const s=snapshot(state),spec=scenarios[state.id];$('scenario').value=state.id;$('description').textContent=spec.description;$('progress').textContent=`${state.step} / ${spec.steps.length}`;$('deliveries').textContent=s.deliveries;$('receipt').textContent=s.receipt;$('verdict').textContent=s.done?spec.verdict:state.step?spec.steps[state.step-1][0]:'Ready to begin.';$('run').disabled=s.done||!!timer;$('step').disabled=s.done||!!timer;$('timeline').replaceChildren(...spec.steps.map(([title,detail],i)=>{const li=document.createElement('li');li.className='trace'+(i<state.step?' active':'');li.dataset.number=String(i+1);const strong=document.createElement('strong'),p=document.createElement('p');strong.textContent=title;p.textContent=i<state.step?detail:'Waiting for this step.';li.append(strong,p);return li;}));$('restart').hidden=!(s.done&&state.id==='crash');$('guarded').disabled=state.guarded;$('naive').disabled=state.naive;$('guard-result').textContent=state.guarded?'Blocked · 1 delivery':'Awaiting restart';$('guard-detail').textContent=state.guarded?'Unresolved start retained. No new callback is invoked.':'The same intact ledger is reused.';$('naive-result').textContent=state.naive?'Retried · 2 deliveries':'Awaiting retry';$('naive-detail').textContent=state.naive?'A second non-idempotent delivery duplicates the effect.':'An intentionally simplistic retry.';}
function select(id){const next=initial(id);stop();state=next;render();}
function step(){state=advance(state);render();}
function run(){stop();state={...state,step:scenarios[state.id].steps.length};render();return snapshot(state);}
$('scenario').onchange=e=>select(e.target.value);$('reset').onclick=()=>select(state.id);$('step').onclick=step;$('run').onclick=()=>{step();if(snapshot(state).done)return;timer=setInterval(()=>{state=advance(state);if(snapshot(state).done)stop();render();},850);render();};for(const mode of ['guarded','naive'])$(mode).onclick=()=>{state=restart(state,mode);render();};
// Optional browser-native tools use the same state transitions as the visible controls.
if(navigator.modelContext?.registerTool){try{navigator.modelContext.registerTool({name:'inspect_simulation',description:'Read the ThreeLineage illustrative simulation, not a live backend.',inputSchema:{type:'object',properties:{},additionalProperties:false},execute:async()=>({content:[{type:'text',text:JSON.stringify(snapshot(state))}]})});navigator.modelContext.registerTool({name:'run_simulation',description:'Run a selected illustrative failure scenario. No external effects.',inputSchema:{type:'object',properties:{scenario:{type:'string',enum:Object.keys(scenarios)}},required:['scenario'],additionalProperties:false},execute:async({scenario})=>{select(scenario);return {content:[{type:'text',text:JSON.stringify(run())}]};}});}catch{/* Optional capability; UI remains fully functional. */}}
render();
