export const scenarios = {
 crash: {name:'The missing receipt',description:'Delivery succeeds. The process stops before recording completion.',steps:[['Intent accepted','The request passes the illustrative policy gate.',0,'Not recorded'],['Execution reserved','A durable start marker is assumed to be stored before delivery.',0,'Pending'],['Delivery completed','The external effect has happened once.',1,'Pending'],['Process interrupted','No completion receipt was recorded. The action remains unresolved.',1,'Missing']],verdict:'Unresolved · restart blocked'},
 normal: {name:'Successful execution',description:'The action and its completion receipt are both recorded.',steps:[['Intent accepted','The request passes the illustrative policy gate.',0,'Not recorded'],['Execution reserved','The start marker is recorded.',0,'Pending'],['Delivery completed','The external effect happens once.',1,'Pending'],['Receipt recorded','The action has a recorded completion.',1,'Complete']],verdict:'Completed · receipt present'},
 veto: {name:'Policy veto',description:'The policy rejects the request before execution.',steps:[['Intent inspected','The request reaches the illustrative policy gate.',0,'Not recorded'],['Policy denied','The callback is not invoked. No delivery occurs.',0,'Not applicable']],verdict:'Denied · no delivery'},
 storage: {name:'Reservation storage failure',description:'The reservation cannot be confirmed durable.',steps:[['Intent accepted','The request passes policy.',0,'Not recorded'],['Persistence failed','Durability cannot be confirmed. The callback is not invoked; written bytes may remain.',0,'Not recorded']],verdict:'Stopped · no delivery'},
 terminal: {name:'Recorded completion failure',description:'Explore the boundary: a recorded terminal failure is not an unresolved start.',steps:[['Execution reserved','A start marker is recorded.',0,'Pending'],['Delivery completed','The effect happens before the completion problem.',1,'Pending'],['Terminal failure recorded','A recorded COMPLETION_RECORDING_FAILED can permit future work. This is not universal duplicate prevention.',1,'Terminal failure']],verdict:'Terminal failure · future work may proceed'}
};
export function initial(id='crash'){if(!scenarios[id])throw Error('Unknown scenario');return {id,step:0,guarded:false,naive:false};}
export function advance(s){return {...s,step:Math.min(s.step+1,scenarios[s.id].steps.length)};}
export function restart(s,mode){if(!['guarded','naive'].includes(mode))throw Error('Unknown restart mode');if(s.id!=='crash'||s.step!==scenarios.crash.steps.length)throw Error('Finish the interruption scenario first');return {...s,[mode]:true};}
export function snapshot(s){const spec=scenarios[s.id], event=spec.steps[s.step-1];return {...s,name:spec.name,done:s.step===spec.steps.length,deliveries:event?.[2]??0,receipt:event?.[3]??'Not recorded',comparisonDeliveries:s.naive?2:null};}
